// Local mock data for safe frontend integration work.
// This file is intentionally static and contains no live backend connection.
// When the future API layer is ready, the frontend service should fetch
// from that API instead of reading from this local mock module.

export const financeAdjustmentsMockResponse = {
  items: [
    {
      month: '2025-01-01',
      companyId: 'CO-101',
      employeeId: 'EE-1001',
      territory: 'United Kingdom',
      primaryAspect: 'Payroll correction',
      adjustmentUsd: -1200,
      absoluteAdjustmentUsd: 1200,
      confidence: 0.94,
    },
    {
      month: '2025-01-01',
      companyId: 'CO-102',
      employeeId: 'EE-1002',
      territory: 'South Africa',
      primaryAspect: 'Tax alignment',
      adjustmentUsd: 850,
      absoluteAdjustmentUsd: 850,
      confidence: 0.89,
    },
    {
      month: '2025-02-01',
      companyId: 'CO-101',
      employeeId: 'EE-1003',
      territory: 'Germany',
      primaryAspect: 'Benefits adjustment',
      adjustmentUsd: -430,
      absoluteAdjustmentUsd: 430,
      confidence: 0.81,
    },
    {
      month: '2025-02-01',
      companyId: 'CO-104',
      employeeId: 'EE-1004',
      territory: 'United States',
      primaryAspect: 'Payroll correction',
      adjustmentUsd: 2750,
      absoluteAdjustmentUsd: 2750,
      confidence: 0.97,
    },
    {
      month: '2025-03-01',
      companyId: 'CO-105',
      employeeId: 'EE-1005',
      territory: 'Canada',
      primaryAspect: 'FX true-up',
      adjustmentUsd: -610,
      absoluteAdjustmentUsd: 610,
      confidence: 0.76,
    },
    {
      month: '2025-03-01',
      companyId: 'CO-102',
      employeeId: 'EE-1006',
      territory: 'South Africa',
      primaryAspect: 'Payroll correction',
      adjustmentUsd: 1425,
      absoluteAdjustmentUsd: 1425,
      confidence: 0.92,
    },
    {
      month: '2025-04-01',
      companyId: 'CO-106',
      employeeId: 'EE-1007',
      territory: 'Brazil',
      primaryAspect: 'Tax alignment',
      adjustmentUsd: -980,
      absoluteAdjustmentUsd: 980,
      confidence: 0.88,
    },
    {
      month: '2025-04-01',
      companyId: 'CO-101',
      employeeId: 'EE-1008',
      territory: 'United Kingdom',
      primaryAspect: 'Benefits adjustment',
      adjustmentUsd: 540,
      absoluteAdjustmentUsd: 540,
      confidence: 0.83,
    },
  ],
};
