// Local mock data for safe frontend integration work.
// This file is intentionally static and contains no live backend connection.
// When the future API layer is ready, the frontend service should fetch
// from that API instead of reading from this local mock module.

export const financeAdjustmentsMockResponse = {
  items: [
    {
      month: '2025-01-01',
      companyId: 'CO-101',
      employeeId: 'EE-1001',
      territory: 'United Kingdom',
      primaryAspect: 'Payroll correction',
      adjustmentUsd: -1200,
      absoluteAdjustmentUsd: 1200,
      confidence: 0.94,
    },
    {
      month: '2025-01-01',
      companyId: 'CO-102',
      employeeId: 'EE-1002',
      territory: 'South Africa',
      primaryAspect: 'Tax alignment',
      adjustmentUsd: 850,
      absoluteAdjustmentUsd: 850,
      confidence: 0.89,
    },
    {
      month: '2025-02-01',
      companyId: 'CO-101',
      employeeId: 'EE-1003',
      territory: 'Germany',
      primaryAspect: 'Benefits adjustment',
      adjustmentUsd: -430,
      absoluteAdjustmentUsd: 430,
      confidence: 0.81,
    },
    {
      month: '2025-02-01',
      companyId: 'CO-104',
      employeeId: 'EE-1004',
      territory: 'United States',
      primaryAspect: 'Payroll correction',
      adjustmentUsd: 2750,
      absoluteAdjustmentUsd: 2750,
      confidence: 0.97,
    },
    {
      month: '2025-03-01',
      companyId: 'CO-105',
      employeeId: 'EE-1005',
      territory: 'Canada',
      primaryAspect: 'FX true-up',
      adjustmentUsd: -610,
      absoluteAdjustmentUsd: 610,
      confidence: 0.76,
    },
    {
      month: '2025-03-01',
      companyId: 'CO-102',
      employeeId: 'EE-1006',
      territory: 'South Africa',
      primaryAspect: 'Payroll correction',
      adjustmentUsd: 1425,
      absoluteAdjustmentUsd: 1425,
      confidence: 0.92,
    },
    {
      month: '2025-04-01',
      companyId: 'CO-106',
      employeeId: 'EE-1007',
      territory: 'Brazil',
      primaryAspect: 'Tax alignment',
      adjustmentUsd: -980,
      absoluteAdjustmentUsd: 980,
      confidence: 0.88,
    },
    {
      month: '2025-04-01',
      companyId: 'CO-101',
      employeeId: 'EE-1008',
      territory: 'United Kingdom',
      primaryAspect: 'Benefits adjustment',
      adjustmentUsd: 540,
      absoluteAdjustmentUsd: 540,
      confidence: 0.83,
    },
  ],
};

export const companyHealthMockResponse = {
  items: [
    {
      companyId: 'CO-101',
      scoreDate: '2025-04-30',
      score: 42,
      rag: 'Red',
      lastUpdated: '2025-05-01T08:15:00Z',
      metricCountEnabled: 8,
      metricCountSuccess: 4,
      growth: {
        rag: 'Red',
        status: 'Contraction risk',
        value: '-12% net revenue movement',
        action: 'Review contraction pipeline and commercial recovery plan',
        detail: 'Expansion pipeline slowed for two consecutive review cycles.',
        priority: 'High',
      },
      csm: {
        rag: 'Amber',
        status: 'Coverage gap',
        value: 'Named owner assigned',
        action: 'Increase cadence for executive check-ins',
        detail: 'Customer success contact exists, but engagement is inconsistent.',
        priority: 'Medium',
      },
      nps: {
        rag: 'Red',
        status: 'Detractor trend',
        value: 'Latest survey negative',
        action: 'Run recovery outreach with sponsor',
        detail: 'Most recent feedback highlighted response-time dissatisfaction.',
        priority: 'High',
      },
      support: {
        rag: 'Red',
        status: 'Escalation pressure',
        value: 'High open incident load',
        ticketCount: 14,
        criticalCount: 3,
        avgScore: 2.1,
        avgHours: 41.5,
        action: 'Triage critical cases and publish follow-up plan',
        detail: 'Three severe incidents remain active beyond target resolution time.',
        priority: 'High',
      },
    },
    {
      companyId: 'CO-102',
      scoreDate: '2025-04-30',
      score: 63,
      rag: 'Amber',
      lastUpdated: '2025-05-01T08:20:00Z',
      metricCountEnabled: 8,
      metricCountSuccess: 6,
      growth: {
        rag: 'Amber',
        status: 'Flat growth',
        value: '0% month-on-month',
        action: 'Monitor expansion opportunities',
        detail: 'Revenue stable but pipeline momentum is light.',
        priority: 'Medium',
      },
      csm: {
        rag: 'Green',
        status: 'Healthy coverage',
        value: 'Regular engagement',
        action: '',
        detail: 'Named CSM and sponsor relationship remain active.',
        priority: 'Low',
      },
      nps: {
        rag: 'Amber',
        status: 'Mixed sentiment',
        value: 'Passive responses',
        action: 'Capture qualitative feedback in next review',
        detail: '',
        priority: 'Medium',
      },
      support: {
        rag: 'Amber',
        status: 'Moderate support load',
        value: 'Recent service tickets elevated',
        ticketCount: 6,
        criticalCount: 1,
        avgScore: 3.4,
        avgHours: 19.2,
        action: 'Track repeat issues and root causes',
        detail: 'Ticket volumes rose after regional onboarding activity.',
        priority: 'Medium',
      },
    },
    {
      companyId: 'CO-103',
      scoreDate: '2025-04-30',
      score: 81,
      rag: 'Green',
      lastUpdated: '2025-05-01T08:25:00Z',
      metricCountEnabled: 8,
      metricCountSuccess: 8,
      growth: {
        rag: 'Green',
        status: 'Healthy expansion',
        value: '+8% month-on-month',
        action: '',
        detail: 'Expansion pipeline closed successfully this month.',
        priority: 'Low',
      },
      csm: {
        rag: 'Green',
        status: 'Strong relationship',
        value: 'Quarterly plan on track',
        action: '',
        detail: 'Leadership sponsor and delivery team are aligned.',
        priority: 'Low',
      },
      nps: {
        rag: 'Green',
        status: 'Promoter trend',
        value: 'Recent positive survey',
        action: 'Capture case study opportunity',
        detail: 'Feedback points to strong onboarding and payroll confidence.',
        priority: 'Low',
      },
      support: {
        rag: 'Green',
        status: 'Low support friction',
        value: 'Minimal open ticket volume',
        ticketCount: 2,
        criticalCount: 0,
        avgScore: 4.6,
        avgHours: 6.1,
        action: '',
        detail: '',
        priority: 'Low',
      },
    },
    {
      companyId: 'CO-104',
      scoreDate: '2025-04-30',
      score: 55,
      rag: 'Amber',
      lastUpdated: '2025-05-01T08:32:00Z',
      metricCountEnabled: 8,
      metricCountSuccess: 5,
      growth: {
        rag: 'Amber',
        status: 'Delayed expansion',
        value: 'Pipeline slipped one month',
        action: 'Reconfirm commercial next steps',
        detail: 'Upsell discussion postponed after procurement review.',
        priority: 'Medium',
      },
      csm: {
        rag: 'Red',
        status: 'Engagement risk',
        value: 'QBR overdue',
        action: 'Schedule executive health review',
        detail: 'No formal success review completed this quarter.',
        priority: 'High',
      },
      nps: {
        rag: 'Amber',
        status: 'No recent survey',
        value: '',
        action: 'Request updated sentiment signal',
        detail: '',
        priority: 'Medium',
      },
      support: {
        rag: 'Amber',
        status: 'Backlog building',
        value: 'Several medium-priority cases open',
        ticketCount: 8,
        criticalCount: 0,
        avgScore: 3.1,
        avgHours: 24.7,
        action: 'Close aging tickets before next review',
        detail: 'Most cases are non-critical but exceeding normal cycle time.',
        priority: 'Medium',
      },
    },
    {
      companyId: 'CO-105',
      scoreDate: '2025-04-30',
      score: 37,
      rag: 'Red',
      lastUpdated: '2025-05-01T08:40:00Z',
      metricCountEnabled: 8,
      metricCountSuccess: 3,
      growth: {
        rag: 'Red',
        status: 'Revenue decline',
        value: '-18% month-on-month',
        action: 'Escalate churn-prevention plan',
        detail: 'Usage and commercial indicators declined together.',
        priority: 'High',
      },
      csm: {
        rag: 'Red',
        status: 'No active plan',
        value: 'Owner transition in progress',
        action: 'Assign permanent owner and recovery cadence',
        detail: '',
        priority: 'High',
      },
      nps: {
        rag: 'Amber',
        status: 'No fresh data',
        value: '',
        action: '',
        detail: 'No survey response in the current quarter.',
        priority: 'Low',
      },
      support: {
        rag: 'Red',
        status: 'Critical support concern',
        value: 'Multiple escalations',
        ticketCount: 11,
        criticalCount: 2,
        avgScore: 1.9,
        avgHours: 52.3,
        action: 'Open incident review and service recovery plan',
        detail: 'Average resolution time has more than doubled since last month.',
        priority: 'High',
      },
    },
    {
      companyId: 'CO-106',
      scoreDate: '2025-04-30',
      score: 74,
      rag: 'Green',
      lastUpdated: '2025-05-01T08:45:00Z',
      metricCountEnabled: 8,
      metricCountSuccess: 7,
      growth: {
        rag: 'Green',
        status: 'Stable growth',
        value: '+4% month-on-month',
        action: '',
        detail: '',
        priority: 'Low',
      },
      csm: {
        rag: 'Green',
        status: 'High engagement',
        value: 'Success plan current',
        action: '',
        detail: 'Quarterly milestones are complete.',
        priority: 'Low',
      },
      nps: {
        rag: 'Green',
        status: 'Positive sentiment',
        value: 'Promoter',
        action: '',
        detail: '',
        priority: 'Low',
      },
      support: {
        rag: 'Amber',
        status: 'Watch support trend',
        value: 'More requests than usual',
        ticketCount: 5,
        criticalCount: 0,
        avgScore: 3.8,
        avgHours: 11.4,
        action: 'Watch for repeat patterns next cycle',
        detail: '',
        priority: 'Low',
      },
    },
  ],
};

export const productNewsMockResponse = {
  items: [
    {
      id: 'news-001',
      category: 'industry_regulatory',
      categoryLabel: 'Industry / Regulatory',
      headline: 'EU Platform Workers Directive transposition deadline approaches',
      actor: '',
      actorType: '',
      summary: 'Several EU member states are releasing draft implementation rules ahead of the platform workers directive deadline, with new tests likely to affect contractor and EOR models.',
      insight: 'Keep an eye on classification risk and country-specific implementation timing.',
      sourceUrl: 'https://ec.europa.eu/social/main.jsp?catId=89&furtherNews=yes',
      sourceDomain: 'ec.europa.eu',
      dateText: '2026-05-01',
      itemDate: '2026-05-01',
      researchedAt: '2026-05-03',
      runType: 'daily',
      tag: '',
      region: 'European Union',
      eventType: '',
      amount: '',
      stage: '',
      investors: '',
      sentiment: '',
      theme: '',
      descriptor: 'Classification risk',
    },
    {
      id: 'news-002',
      category: 'competitor_moves',
      categoryLabel: 'Competitor Moves',
      headline: 'Rippling expands global payroll to 15 new countries',
      actor: 'Rippling',
      actorType: 'company',
      summary: 'Rippling expanded payroll coverage across additional markets, positioning itself more directly against other multi-country payroll platforms.',
      insight: 'Coverage expansion is a strong signal for product breadth and enterprise sales positioning.',
      sourceUrl: 'https://www.rippling.com/blog',
      sourceDomain: 'rippling.com',
      dateText: '2026-04-30',
      itemDate: '2026-04-30',
      researchedAt: '2026-05-03',
      runType: 'daily',
      tag: 'expansion',
      region: '',
      eventType: '',
      amount: '',
      stage: '',
      investors: '',
      sentiment: '',
      theme: '',
      descriptor: 'Expansion',
    },
    {
      id: 'news-003',
      category: 'ai_model_releases',
      categoryLabel: 'AI Model Releases',
      headline: 'GPT-5',
      actor: 'OpenAI',
      actorType: 'company',
      summary: 'OpenAI introduced a next-generation flagship model that combines stronger reasoning with multimodal understanding.',
      insight: 'Useful to track for workflow automation, document analysis, and product research pipelines.',
      sourceUrl: 'https://openai.com/index/gpt-5/',
      sourceDomain: 'openai.com',
      dateText: '2025-04-16',
      itemDate: '2025-04-16',
      researchedAt: '2026-05-03',
      runType: 'daily',
      tag: '',
      region: '',
      eventType: '',
      amount: '',
      stage: '',
      investors: '',
      sentiment: '',
      theme: '',
      descriptor: 'GPT-5',
    },
    {
      id: 'news-004',
      category: 'ai_tools_hr',
      categoryLabel: 'AI Tools for HR',
      headline: 'Gusto AI Tax Filing Assistant',
      actor: 'Gusto',
      actorType: 'maker',
      summary: 'Gusto released an AI assistant that helps automate tax filing preparation and explain filing obligations in plain English.',
      insight: 'Signals continued pressure toward assistant-led payroll workflows and lower-friction self-service tooling.',
      sourceUrl: 'https://www.gusto.com/blog/ai-tax-filing-assistant',
      sourceDomain: 'gusto.com',
      dateText: '2026-05-02',
      itemDate: '2026-05-02',
      researchedAt: '2026-05-03',
      runType: 'daily',
      tag: '',
      region: '',
      eventType: '',
      amount: '',
      stage: '',
      investors: '',
      sentiment: '',
      theme: '',
      descriptor: 'Payroll AI',
    },
    {
      id: 'news-005',
      category: 'market_intelligence',
      categoryLabel: 'Market Intelligence',
      headline: 'McKinsey: distributed teams now the default for 60% of multinational firms',
      actor: 'McKinsey & Company',
      actorType: 'publisher',
      summary: 'A new McKinsey report suggests distributed team operating models have become the default for a majority of multinational companies.',
      insight: 'Strengthens the strategic case for products that simplify globally distributed employment and payroll operations.',
      sourceUrl: 'https://www.mckinsey.com/capabilities/people-and-organizational-performance/our-insights/distributed-teams-2026',
      sourceDomain: 'mckinsey.com',
      dateText: '2026-05-01',
      itemDate: '2026-05-01',
      researchedAt: '2026-05-03',
      runType: 'daily',
      tag: '',
      region: '',
      eventType: '',
      amount: '',
      stage: '',
      investors: '',
      sentiment: '',
      theme: '',
      descriptor: 'Remote work trend',
    },
  ],
};

export const actionsMockResponse = {
  items: [
    {
      id: 'run_diagnostics',
      name: 'Run diagnostics',
      description: 'Check that dashboard datasets and server-side action wiring are reachable.',
      category: 'Diagnostics',
      impact: 'safe',
      defaultMode: 'dry_run',
      allowLiveRun: false,
      liveEnabled: false,
      buttonLabel: 'Run diagnostics',
    },
    {
      id: 'recalculate_company_health',
      name: 'Recalculate company health',
      description: 'Run the current company health summary calculation without writing back to the database.',
      category: 'Calculations',
      impact: 'internal',
      defaultMode: 'dry_run',
      allowLiveRun: false,
      liveEnabled: false,
      buttonLabel: 'Preview calculation',
    },
    {
      id: 'send_test_webhook',
      name: 'Send test webhook',
      description: 'Preview or send a test payload to the server-side allowlisted webhook target.',
      category: 'Webhooks',
      impact: 'integration',
      defaultMode: 'dry_run',
      allowLiveRun: true,
      liveEnabled: false,
      buttonLabel: 'Preview webhook',
    },
  ],
};

export const runMockAction = (actionId, payload = {}) => {
  const mode = payload.mode || 'dry_run';
  const ranAt = new Date().toISOString();

  switch (actionId) {
    case 'run_diagnostics':
      return {
        ok: true,
        actionId,
        status: 'success',
        message: 'Diagnostics completed in local mock mode.',
        mode,
        ranAt,
        result: {
          datasetChecks: {
            financeAdjustments: 'mock-ready',
            companyHealth: 'mock-ready',
          },
          webhookConfigured: false,
          environment: 'local',
        },
      };
    case 'recalculate_company_health':
      return {
        ok: true,
        actionId,
        status: 'success',
        message: 'Company health recalculation preview completed in local mode.',
        mode,
        ranAt,
        result: {
          averageScore: 59,
          redCompanies: 2,
          amberCompanies: 2,
          greenCompanies: 2,
        },
      };
    case 'send_test_webhook':
      return {
        ok: true,
        actionId,
        status: 'success',
        message: mode === 'live'
          ? 'Live webhook sending is disabled in local mock mode.'
          : 'Webhook preview payload generated in local mode.',
        mode,
        ranAt,
        result: {
          wouldSend: mode === 'live' ? false : true,
          webhookConfigured: false,
          payloadPreview: {
            source: 'actions-page',
            actionId,
            mode,
          },
        },
      };
    default:
      return {
        ok: false,
        actionId,
        status: 'failed',
        message: `Unknown mock action: ${actionId}`,
        mode,
        ranAt,
        result: {},
      };
  }
};
